table:
  name: user_settings
  schema: public
configuration:
  column_config:
    user_id:
      custom_name: userId
  custom_column_names:
    user_id: userId
  custom_name: userSettings
  custom_root_fields:
    delete: deleteUserSettings
    delete_by_pk: deleteUserSettingsByPk
    insert: insertUserSettings
    insert_one: insertUserSettingsOne
    select: userSettings
    select_aggregate: userSettingsAggregate
    select_by_pk: userSettingsByPk
    select_stream: userSettingsStream
    update: updateUserSettings
    update_by_pk: updateUserSettingsByPk
object_relationships:
  - name: user
    using:
      foreign_key_constraint_on: user_id
select_permissions:
  - role: hasura
    permission:
      columns:
        - user_id
      filter: {}
      allow_aggregations: true
  - role: user
    permission:
      columns:
        - user_id
      filter:
        user_id:
          _eq: X-Hasura-User-Id
delete_permissions:
  - role: user
    permission:
      backend_only: false
      filter:
        user_id:
          _eq: X-Hasura-User-Id
