table:
  name: user_settings
  schema: public
configuration:
  column_config:
    wallet_address:
      custom_name: walletAddress
  custom_column_names:
    wallet_address: walletAddress
  custom_name: userSettings
  custom_root_fields:
    delete: deleteUserSettings
    delete_by_pk: deleteUserSettingsByPk
    insert: insertUserSettings
    insert_one: insertUserSettingsOne
    select: userSettings
    select_aggregate: userSettingsAggregate
    select_by_pk: userSettingsByPk
    select_stream: userSettingsStream
    update: updateUserSettings
    update_by_pk: updateUserSettingsByPk
object_relationships:
  - name: userProfile
    using:
      manual_configuration:
        column_mapping:
          wallet_address: wallet_address
        insertion_order: null
        remote_table:
          name: user_profile
          schema: public
select_permissions:
  - role: hasura
    permission:
      columns:
        - wallet_address
      filter: {}
      allow_aggregations: true
  - role: user
    permission:
      columns:
        - wallet_address
      filter:
        wallet_address:
          _eq: X-Hasura-User-Id
delete_permissions:
  - role: user
    permission:
      backend_only: false
      filter:
        wallet_address:
          _eq: X-Hasura-User-Id
